name: Build Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install system dependencies
      run: |
        brew update
        brew install gettext
        brew link gettext --force
        
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: 3.8
        
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -y pandas numpy pip
        pip install -r requirements.txt
        pip install pillow
        
    - name: Create icon
      shell: bash -l {0}
      run: |
        cd mac
        python create_icns.py
        
    - name: Build Mac app
      shell: bash -l {0}
      run: |
        cd mac
        python build_mac.py
        
    - name: Package release
      run: |
        cd mac/dist
        zip -r ../../Alpha_Tool_Mac.zip ./*
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Alpha_Tool_Mac.zip
        asset_name: Alpha_Tool_Mac.zip
        asset_content_type: application/zip 